eureka:
  client:
    serviceUrl:
      defaultZone: http://ADESH-LAPTOP:8761/eureka
  instance:
    hostname: ADESH-LAPTOP
    registerWithEureka: true
    fetchRegistry: true
    preferIpAddress: false
